import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ToTop from "@/components/to-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative bg-veryLightGray text-veryDarkBlue dark:bg-veryDarkBlue dark:text-white ${inter.className}`}
      >
        <Header />
        <main className="overflow-hidden px-6 py-16 lg:px-24">{children}</main>

        <ToTop />
      </body>
    </html>
  );
}
